### ISSUE TITLE
Proposal: alternative signal declaration syntax

### ISSUE THREAD

**Issue by misanthrop** [copperspice/cs_signal#2]
Currently the syntax is quite ugly:

```cpp
SIGNAL_1(void someSignal(int arg1, int arg2))
SIGNAL_2(someSignal, arg1, arg2)
```

Duplication of the signal name and argument names can't be avoided without complicated macro and even more strange syntax (like Boost::Fusion).

But the following alternative seems equivalent, but looks a bit cleaner to me:

```cpp
void someSignal(int arg1, int arg2) { ACTIVATE(someSignal, arg1, arg2); }
```

or

```cpp
void someSignal(int arg1, int arg2) ACTIVATE(someSignal, arg1, arg2)
```

**Comment by agserm** [comment]
The syntax you propose might work for the simple use case in cs_signal. However, it does not work in the case that the signal is overloaded, and it is not sufficient for the additional reflection requirements in CopperSpice. Since this simplified syntax does not work in all cases, it seems like having a standard syntax that works everywhere is the best option.
